[package]
name = "etornie-ip-token"
version = "0.1.0"
description = "Soul-bound Case NFT program for Etornie: Token-2022 + Light Protocol compression"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "etornie_ip_token"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]

[dependencies]
anchor-lang = "1.0.2"
anchor-spl = { version = "0.31.1", features = ["token", "token_2022", "associated_token"] }
