#!/usr/bin/env node
/* eslint-disable no-console */
/**
 * Extract Groth16 verifying key from a snarkjs `verification_key.json`
 * into a Rust constant file compatible with groth16-solana v0.2.0.
 *
 * Adapted from the upstream `parse_vk_to_rust.js` script bundled in
 * groth16-solana v0.2.0 (MIT, Light Protocol). Reuse instead of rewrite
 * preserves the audited byte-layout logic.
 *
 * Changes vs upstream:
 *   - Target field name is `vk_gamme_g2` (typo kept — it matches the
 *     Groth16Verifyingkey struct field in groth16-solana v0.2.0).
 *   - Output path + const name are CLI arguments (not hard-coded).
 *   - Adds a header with input-file sha256 so drift is visible in git diff.
 *   - Sanity-checks `protocol=groth16` and `curve=bn128` before emitting.
 *
 * Byte layout produced (all big-endian, matching the Solana alt_bn128 syscalls):
 *   G1 (64 bytes)  : x_be || y_be
 *   G2 (128 bytes) : x.c1_be || x.c0_be || y.c1_be || y.c0_be
 *
 * Usage:
 *   node scripts/extract_vk.js <input.json> <output_dir> [output_filename]
 *
 * Example:
 *   node scripts/extract_vk.js \
 *     circuits/build/hello_world/verification_key.json \
 *     programs/etornie-zk-verifier/src \
 *     groth16_vk.rs
 */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { utils } = require('ffjavascript');

const { unstringifyBigInts, leInt2Buff } = utils;

function usage(msg) {
  if (msg) console.error(`error: ${msg}`);
  console.error(
    'Usage: node scripts/extract_vk.js <input.json> <output_dir> [output_filename]'
  );
  process.exit(1);
}

function g1ToBE(coord) {
  // BigInt → 32-byte LE Buffer → reverse → 32-byte BE array
  return Array.from(leInt2Buff(unstringifyBigInts(coord), 32)).reverse();
}

function g2ToBE(pair) {
  // snarkjs JSON G2 element = [c0, c1] (each BigInt string).
  // Concat LE(c0) || LE(c1), reverse full 64 bytes → [c1_be, c0_be].
  const c0 = Array.from(leInt2Buff(unstringifyBigInts(pair[0]), 32));
  const c1 = Array.from(leInt2Buff(unstringifyBigInts(pair[1]), 32));
  const tmp = c0.concat(c1).reverse();
  return [tmp.slice(0, 32), tmp.slice(32, 64)];
}

function renderBytes(arr) {
  return arr.join(', ');
}

function main() {
  const inputPath = process.argv[2];
  const outputDir = process.argv[3];
  const outputFile = process.argv[4] || 'groth16_vk.rs';

  if (!inputPath) usage('inputPath not specified');
  if (!outputDir) usage('outputDir not specified');

  const raw = fs.readFileSync(inputPath, 'utf8');
  const jsonHash = crypto.createHash('sha256').update(raw).digest('hex');
  const vk = JSON.parse(raw);

  if (vk.protocol !== 'groth16') {
    throw new Error(`unsupported protocol: ${vk.protocol} (expected groth16)`);
  }
  if (vk.curve !== 'bn128') {
    throw new Error(`unsupported curve: ${vk.curve} (expected bn128)`);
  }
  if (!Array.isArray(vk.IC) || vk.IC.length < 2) {
    throw new Error('IC array missing or too short (expected length >= 2)');
  }

  // Transform in place to byte arrays (mirrors upstream parse_vk_to_rust.js).
  for (let j = 0; j < vk.vk_alpha_1.length - 1; j++) {
    vk.vk_alpha_1[j] = g1ToBE(vk.vk_alpha_1[j]);
  }
  for (const field of ['vk_beta_2', 'vk_gamma_2', 'vk_delta_2']) {
    for (let j = 0; j < vk[field].length - 1; j++) {
      vk[field][j] = g2ToBE(vk[field][j]);
    }
  }
  for (let j = 0; j < vk.IC.length; j++) {
    for (let z = 0; z < vk.IC[j].length - 1; z++) {
      vk.IC[j][z] = g1ToBE(vk.IC[j][z]);
    }
  }

  const outPath = path.join(outputDir, outputFile);
  const relSource = path.relative(path.dirname(outPath), inputPath);

  const lines = [];
  lines.push('// THIS FILE IS AUTO-GENERATED BY scripts/extract_vk.js — DO NOT EDIT MANUALLY.');
  lines.push(`// Source  : ${relSource}`);
  lines.push(`// SHA-256 : ${jsonHash}`);
  lines.push('// Regenerate: node scripts/extract_vk.js <input.json> <output_dir> [output_filename]');
  lines.push('//');
  lines.push('// Note: the field name `vk_gamme_g2` (typo) is intentional — it matches the');
  lines.push('//       Groth16Verifyingkey struct in groth16-solana v0.2.0 verbatim.');
  lines.push('');
  lines.push('use groth16_solana::groth16::Groth16Verifyingkey;');
  lines.push('');
  lines.push('pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {');
  lines.push(`    nr_pubinputs: ${vk.IC.length},`);
  lines.push('');

  // vk_alpha_g1 : 64-byte G1 point
  lines.push('    vk_alpha_g1: [');
  for (let j = 0; j < vk.vk_alpha_1.length - 1; j++) {
    lines.push(`        ${renderBytes(vk.vk_alpha_1[j])},`);
  }
  lines.push('    ],');
  lines.push('');

  // G2 fields
  const g2Emit = (jsonKey, rustField) => {
    lines.push(`    ${rustField}: [`);
    for (let j = 0; j < vk[jsonKey].length - 1; j++) {
      for (let z = 0; z < 2; z++) {
        lines.push(`        ${renderBytes(vk[jsonKey][j][z])},`);
      }
    }
    lines.push('    ],');
    lines.push('');
  };
  g2Emit('vk_beta_2', 'vk_beta_g2');
  g2Emit('vk_gamma_2', 'vk_gamme_g2'); // typo preserved — see header note
  g2Emit('vk_delta_2', 'vk_delta_g2');

  // vk_ic : &[[u8; 64]; N+1]
  lines.push('    vk_ic: &[');
  for (const ic of vk.IC) {
    lines.push('        [');
    for (let j = 0; j < ic.length - 1; j++) {
      lines.push(`            ${renderBytes(ic[j])},`);
    }
    lines.push('        ],');
  }
  lines.push('    ],');
  lines.push('};');
  lines.push('');

  fs.mkdirSync(outputDir, { recursive: true });
  fs.writeFileSync(outPath, lines.join('\n'));

  console.error(`✓ Wrote ${outPath}`);
  console.error(`  source      : ${inputPath}`);
  console.error(`  sha256      : ${jsonHash}`);
  console.error(`  nr_pubinputs: ${vk.IC.length}`);
  console.error(`  IC entries  : ${vk.IC.length}`);
}

main();
